version: "3.10"

services:
  core:
    build:
      args:
        - BASE_IMAGE=ubuntu:22.04
        - PYTHON_VERSION=3.10
      context: ../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - /mnt:/mnt
    ports:
        - 8000:8000